### ISSUE TITLE
2.0.0-alpha-7 Causes Breaking Changes

### ISSUE THREAD

**Issue by rickhousley** [vaticle/homebrew-tap#3]
Commit 98ca4f5 causes breaking interoperability with Workbase. A number of dependencies are not listed as well (lz4, tbb, zstd) which causes issues with the debug flag.

The main page is still promoting distribution of 1.8.4 and I imagine the homebrew tap should be in-line with that.

**Comment by berkanteber** [comment]
I agree, 1.8.4 should be available.

**Comment by vmax** [comment]
@rickhousley thank you for reporting!

>The main page is still promoting distribution of 1.8.4 and I imagine the homebrew tap should be in-line with that.

Happy to inform we've released production version of 2.0.0 and encourage all users to switch to it as it's the only one that is going to be supported going forward. Should you find any bugs with the newest release, feel free to open another issue.
