### ISSUE TITLE
Grakn Homebrew Tap not working.

### ISSUE THREAD

**Issue by rfuisz** [vaticle/homebrew-tap#4]
Happy to provide more data as helpful -- having some trouble installing grakn core using homebrew. 

`Main@MacBook-Pro local % brew install --cask graknlabs/tap/grakn-core
==> Tapping graknlabs/tap
Cloning into '/usr/local/Homebrew/Library/Taps/graknlabs/homebrew-tap'...
remote: Enumerating objects: 173, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 277 (delta 45), reused 156 (delta 29), pack-reused 104
Receiving objects: 100% (277/277), 40.53 KiB | 1.09 MiB/s, done.
Resolving deltas: 100% (75/75), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/graknlabs/homebrew-tap/Formula/grakn-workbase.rb
grakn-workbase: undefined method `cask' for Formulary::FormulaNamespacec91e29884df34b0570d2493802377cd8:Module
Error: Cannot tap graknlabs/tap: invalid syntax in tap!`

**Comment by vmax** [comment]
@rfuisz thank you for reporting in! Would you mind retesting again? The easiest way would probably be:

```
brew untap graknlabs/tap
brew tap graknlabs/tap
```

Also, it should be noted that you probably don't need `--cask` argument when installing Grakn Core (database server): 
`brew install graknlabs/tap/grakn-core`. It would be required if you choose to install Grakn Workbase (visual database client) - `brew install --cask graknlabs/tap/grakn-workbase`.

**Comment by rfuisz** [comment]
Works great now. thanks!

Sent via Superhuman ( ***@***.*** )
